import Head from 'next/head'
import styles from '../styles/Home.module.css'

export async function getStaticProps() {
  return { 
    props:{name:new Date().toLocaleTimeString()},

    revalidate:5
   }
}


export default function Home({ name }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next Apjhgjgjhp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <h1>{name}</h1>
     <h1>Hunting Coder</h1>
     <h2>Populer blogs</h2>
     <ul>
      <li>first blog</li>
      <li>second blog</li>
     </ul>
    </div>
  )
}
